### ISSUE TITLE
unable to run on Windows Server 2012 R2 Standard / code: 4294967295

### ISSUE THREAD

**Issue by eostermueller** [maxsivanov/influxdb-timeshift-proxy#20]
thanks again for the timeshift proxy.  It has been working for us for several months.
Getting the error below running on a Windows 2012 server.  Works just fine on Windows 10.
It probably isn't related, but this machine has zero internet access.
```
11 silly lifecycle influxdb-timeshift-proxy@0.0.8~start: Returned: code: 4294967295  signal: null
12 info lifecycle influxdb-timeshift-proxy@0.0.8~start: Failed to exec start script
13 verbose stack Error: influxdb-timeshift-proxy@0.0.8 start: `node ./bin/www`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid influxdb-timeshift-proxy@0.0.8
```
Here is the environment:
```
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--loglevel" "verbose" "run" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
```

Here is the full log file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--loglevel',
1 verbose cli   'verbose',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle influxdb-timeshift-proxy@0.0.8~prestart: influxdb-timeshift-proxy@0.0.8
6 info lifecycle influxdb-timeshift-proxy@0.0.8~start: influxdb-timeshift-proxy@0.0.8
7 verbose lifecycle influxdb-timeshift-proxy@0.0.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle influxdb-timeshift-proxy@0.0.8~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\EPT\influxdb-timeshift-proxy-master_eto\node_modules\.bin;C:\IBM\ITM\InstallITM;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\IBM\ITM\bin;C:\IBM\ITM\TMAITM6;C:\Program Files\nodejs\;C:\Users\adm-e1033533\AppData\Roaming\npm
9 verbose lifecycle influxdb-timeshift-proxy@0.0.8~start: CWD: C:\EPT\influxdb-timeshift-proxy-master_eto
10 silly lifecycle influxdb-timeshift-proxy@0.0.8~start: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle influxdb-timeshift-proxy@0.0.8~start: Returned: code: 4294967295  signal: null
12 info lifecycle influxdb-timeshift-proxy@0.0.8~start: Failed to exec start script
13 verbose stack Error: influxdb-timeshift-proxy@0.0.8 start: `node ./bin/www`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid influxdb-timeshift-proxy@0.0.8
15 verbose cwd C:\EPT\influxdb-timeshift-proxy-master_eto
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--loglevel" "verbose" "run" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 4294967295
22 error influxdb-timeshift-proxy@0.0.8 start: `node ./bin/www`
22 error Exit status 4294967295
23 error Failed at the influxdb-timeshift-proxy@0.0.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]

```

**Comment by eostermueller** [comment]
...and I confirmed that these are in place:
```
C:\Progra~1\nodejs\node.exe
C:\Progra~1\nodejs\node_modules\npm\bin\npm-cli.js
```

**Comment by eostermueller** [comment]
Also tried this approach:
Wet the env variable:
```
setx /m INFLUXDB localhost:8086
```

executed this:
```
node ./bin/www /d /s /c
```

and got this msg for unix startup:
```
Usage: INFLUXDB=127.0.0.1:8086 npm run start
```

**Comment by Rick-van-Dam** [comment]
The instructions in the readme do not work either I noticed for windows:
```
setx INFLUXDB 192.168.33.11:8086
influxdb-timeshift-proxy
Usage: INFLUXDB=127.0.0.1:8086 npm run start
```

**Comment by eostermueller** [comment]
I got this working by not using npm, and just launching the code with node.
Don't have the syntax in front of me, but that certainly worked.
