### ISSUE TITLE
[Q] running problem, why?

### ISSUE THREAD

**Issue by sanchomuzax** [maxsivanov/influxdb-timeshift-proxy#7]
Hi! I have a problem with running of it. What is the problem? Thnak you!

```
$ sudo INFLUXDB=localhost:8086 npm run start

> influxdb-timeshift-proxy@0.0.4 start /home/attila.virag/influxdb-timeshift-proxy
> node ./bin/www

/home/attila.virag/influxdb-timeshift-proxy/app.js:32
const influx_url = new URL(e.INFLUXDB.match(/^https*:\/\//) ? e.INFLUXDB : `http://${e.INFLUXDB}`);
                   ^

TypeError: URL is not a constructor
    at Object.<anonymous> (/home/attila.virag/influxdb-timeshift-proxy/app.js:32:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/attila.virag/influxdb-timeshift-proxy/bin/www:7:11)
    at Module._compile (module.js:570:32)

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! influxdb-timeshift-proxy@0.0.4 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the influxdb-timeshift-proxy@0.0.4 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the influxdb-timeshift-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs influxdb-timeshift-proxy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls influxdb-timeshift-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/attila.virag/influxdb-timeshift-proxy/npm-debug.log
```

**Comment by maxsivanov** [comment]
It's npm version related. I've updated code to be compatible with 6.11. 
PS. You do not need `sudo` to run this

**Comment by sanchomuzax** [comment]
Thank you! I updated and I think that it is running (GET 200 ...).

I added my influxdb server ip with 8089 port to grafana also. It's complet - sad the grafana. It's ok also.
But I can't use the timeshift function on graph.
I selected the new db as source for graph (the original is "my database", and the new one is "my database timeshift", but "Datasource is not configured to allow this database".

Query Inspector sad:
```
request:Object
method:"GET"
url:"api/datasources/proxy/12/query"
params:Object
db:"my database"
q:"SELECT mean("value") FROM "ct_hs_osszes" WHERE time >= now() - 24h GROUP BY time(10m) fill(null)"
epoch:"ms"
data:null
precision:"ms"
response:Object
message:"Datasource is not configured to allow this database"
```

**Comment by sanchomuzax** [comment]
[SOLVED] I had to add the IP address of my server....

sudo INFLUXDB=x.x.x.x:8086 npm run start

Thank you for your plugin! 👍

**Comment by maxsivanov** [comment]
👍
